/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as ReportLostCatIndexRouteImport } from './routes/report-lost-cat/index'
import { Route as ReportFoundCatIndexRouteImport } from './routes/report-found-cat/index'
import { Route as MapIndexRouteImport } from './routes/map/index'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as LandingPrivacyPolicyRouteImport } from './routes/_landing/privacy-policy'
import { Route as LandingFaqRouteImport } from './routes/_landing/faq'
import { Route as LandingContactUsRouteImport } from './routes/_landing/contact-us'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AuthForgotPasswordCheckEmailRouteImport } from './routes/_auth/forgot-password.check-email'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin.users'
import { Route as AdminAdminContactUsRouteImport } from './routes/_admin/admin.contact-us'
import { Route as AdminAdminCatRequestsRouteImport } from './routes/_admin/admin.cat-requests'

const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportLostCatIndexRoute = ReportLostCatIndexRouteImport.update({
  id: '/report-lost-cat/',
  path: '/report-lost-cat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportFoundCatIndexRoute = ReportFoundCatIndexRouteImport.update({
  id: '/report-found-cat/',
  path: '/report-found-cat/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingPrivacyPolicyRoute = LandingPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LandingRoute,
} as any)
const LandingFaqRoute = LandingFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LandingRoute,
} as any)
const LandingContactUsRoute = LandingContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => LandingRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthForgotPasswordCheckEmailRoute =
  AuthForgotPasswordCheckEmailRouteImport.update({
    id: '/check-email',
    path: '/check-email',
    getParentRoute: () => AuthForgotPasswordRoute,
  } as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminContactUsRoute = AdminAdminContactUsRouteImport.update({
  id: '/admin/contact-us',
  path: '/admin/contact-us',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCatRequestsRoute = AdminAdminCatRequestsRouteImport.update({
  id: '/admin/cat-requests',
  path: '/admin/cat-requests',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof AuthForgotPasswordRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/contact-us': typeof LandingContactUsRoute
  '/faq': typeof LandingFaqRoute
  '/privacy-policy': typeof LandingPrivacyPolicyRoute
  '/': typeof LandingIndexRoute
  '/map': typeof MapIndexRoute
  '/report-found-cat': typeof ReportFoundCatIndexRoute
  '/report-lost-cat': typeof ReportLostCatIndexRoute
  '/admin/cat-requests': typeof AdminAdminCatRequestsRoute
  '/admin/contact-us': typeof AdminAdminContactUsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/forgot-password/check-email': typeof AuthForgotPasswordCheckEmailRoute
  '/admin': typeof AdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof AuthForgotPasswordRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/contact-us': typeof LandingContactUsRoute
  '/faq': typeof LandingFaqRoute
  '/privacy-policy': typeof LandingPrivacyPolicyRoute
  '/': typeof LandingIndexRoute
  '/map': typeof MapIndexRoute
  '/report-found-cat': typeof ReportFoundCatIndexRoute
  '/report-lost-cat': typeof ReportLostCatIndexRoute
  '/admin/cat-requests': typeof AdminAdminCatRequestsRoute
  '/admin/contact-us': typeof AdminAdminContactUsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/forgot-password/check-email': typeof AuthForgotPasswordCheckEmailRoute
  '/admin': typeof AdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_landing': typeof LandingRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_landing/contact-us': typeof LandingContactUsRoute
  '/_landing/faq': typeof LandingFaqRoute
  '/_landing/privacy-policy': typeof LandingPrivacyPolicyRoute
  '/_landing/': typeof LandingIndexRoute
  '/map/': typeof MapIndexRoute
  '/report-found-cat/': typeof ReportFoundCatIndexRoute
  '/report-lost-cat/': typeof ReportLostCatIndexRoute
  '/_admin/admin/cat-requests': typeof AdminAdminCatRequestsRoute
  '/_admin/admin/contact-us': typeof AdminAdminContactUsRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_auth/forgot-password/check-email': typeof AuthForgotPasswordCheckEmailRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/contact-us'
    | '/faq'
    | '/privacy-policy'
    | '/'
    | '/map'
    | '/report-found-cat'
    | '/report-lost-cat'
    | '/admin/cat-requests'
    | '/admin/contact-us'
    | '/admin/users'
    | '/forgot-password/check-email'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/contact-us'
    | '/faq'
    | '/privacy-policy'
    | '/'
    | '/map'
    | '/report-found-cat'
    | '/report-lost-cat'
    | '/admin/cat-requests'
    | '/admin/contact-us'
    | '/admin/users'
    | '/forgot-password/check-email'
    | '/admin'
  id:
    | '__root__'
    | '/_admin'
    | '/_auth'
    | '/_landing'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_landing/contact-us'
    | '/_landing/faq'
    | '/_landing/privacy-policy'
    | '/_landing/'
    | '/map/'
    | '/report-found-cat/'
    | '/report-lost-cat/'
    | '/_admin/admin/cat-requests'
    | '/_admin/admin/contact-us'
    | '/_admin/admin/users'
    | '/_auth/forgot-password/check-email'
    | '/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  LandingRoute: typeof LandingRouteWithChildren
  MapIndexRoute: typeof MapIndexRoute
  ReportFoundCatIndexRoute: typeof ReportFoundCatIndexRoute
  ReportLostCatIndexRoute: typeof ReportLostCatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-lost-cat/': {
      id: '/report-lost-cat/'
      path: '/report-lost-cat'
      fullPath: '/report-lost-cat'
      preLoaderRoute: typeof ReportLostCatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-found-cat/': {
      id: '/report-found-cat/'
      path: '/report-found-cat'
      fullPath: '/report-found-cat'
      preLoaderRoute: typeof ReportFoundCatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/': {
      id: '/map/'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/privacy-policy': {
      id: '/_landing/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof LandingPrivacyPolicyRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/faq': {
      id: '/_landing/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof LandingFaqRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/contact-us': {
      id: '/_landing/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof LandingContactUsRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/forgot-password/check-email': {
      id: '/_auth/forgot-password/check-email'
      path: '/check-email'
      fullPath: '/forgot-password/check-email'
      preLoaderRoute: typeof AuthForgotPasswordCheckEmailRouteImport
      parentRoute: typeof AuthForgotPasswordRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/contact-us': {
      id: '/_admin/admin/contact-us'
      path: '/admin/contact-us'
      fullPath: '/admin/contact-us'
      preLoaderRoute: typeof AdminAdminContactUsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/cat-requests': {
      id: '/_admin/admin/cat-requests'
      path: '/admin/cat-requests'
      fullPath: '/admin/cat-requests'
      preLoaderRoute: typeof AdminAdminCatRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminCatRequestsRoute: typeof AdminAdminCatRequestsRoute
  AdminAdminContactUsRoute: typeof AdminAdminContactUsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminCatRequestsRoute: AdminAdminCatRequestsRoute,
  AdminAdminContactUsRoute: AdminAdminContactUsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthForgotPasswordRouteChildren {
  AuthForgotPasswordCheckEmailRoute: typeof AuthForgotPasswordCheckEmailRoute
}

const AuthForgotPasswordRouteChildren: AuthForgotPasswordRouteChildren = {
  AuthForgotPasswordCheckEmailRoute: AuthForgotPasswordCheckEmailRoute,
}

const AuthForgotPasswordRouteWithChildren =
  AuthForgotPasswordRoute._addFileChildren(AuthForgotPasswordRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LandingRouteChildren {
  LandingContactUsRoute: typeof LandingContactUsRoute
  LandingFaqRoute: typeof LandingFaqRoute
  LandingPrivacyPolicyRoute: typeof LandingPrivacyPolicyRoute
  LandingIndexRoute: typeof LandingIndexRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingContactUsRoute: LandingContactUsRoute,
  LandingFaqRoute: LandingFaqRoute,
  LandingPrivacyPolicyRoute: LandingPrivacyPolicyRoute,
  LandingIndexRoute: LandingIndexRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  LandingRoute: LandingRouteWithChildren,
  MapIndexRoute: MapIndexRoute,
  ReportFoundCatIndexRoute: ReportFoundCatIndexRoute,
  ReportLostCatIndexRoute: ReportLostCatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
