/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as LangLandingRouteImport } from './routes/$lang/_landing'
import { Route as LangAuthRouteImport } from './routes/$lang/_auth'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as LangReportLostCatIndexRouteImport } from './routes/$lang/report-lost-cat/index'
import { Route as LangReportFoundCatIndexRouteImport } from './routes/$lang/report-found-cat/index'
import { Route as LangMapIndexRouteImport } from './routes/$lang/map/index'
import { Route as LangLandingIndexRouteImport } from './routes/$lang/_landing/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin.users'
import { Route as AdminAdminContactUsRouteImport } from './routes/_admin/admin.contact-us'
import { Route as AdminAdminCatRequestsRouteImport } from './routes/_admin/admin.cat-requests'
import { Route as LangLandingPrivacyPolicyRouteImport } from './routes/$lang/_landing/privacy-policy'
import { Route as LangLandingFaqRouteImport } from './routes/$lang/_landing/faq'
import { Route as LangLandingContactUsRouteImport } from './routes/$lang/_landing/contact-us'
import { Route as LangAuthResetPasswordRouteImport } from './routes/$lang/_auth/reset-password'
import { Route as LangAuthRegisterRouteImport } from './routes/$lang/_auth/register'
import { Route as LangAuthLoginRouteImport } from './routes/$lang/_auth/login'
import { Route as LangAuthForgotPasswordRouteImport } from './routes/$lang/_auth/forgot-password'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const LangLandingRoute = LangLandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => LangRoute,
} as any)
const LangAuthRoute = LangAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => LangRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const LangReportLostCatIndexRoute = LangReportLostCatIndexRouteImport.update({
  id: '/report-lost-cat/',
  path: '/report-lost-cat/',
  getParentRoute: () => LangRoute,
} as any)
const LangReportFoundCatIndexRoute = LangReportFoundCatIndexRouteImport.update({
  id: '/report-found-cat/',
  path: '/report-found-cat/',
  getParentRoute: () => LangRoute,
} as any)
const LangMapIndexRoute = LangMapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => LangRoute,
} as any)
const LangLandingIndexRoute = LangLandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangLandingRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminContactUsRoute = AdminAdminContactUsRouteImport.update({
  id: '/admin/contact-us',
  path: '/admin/contact-us',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCatRequestsRoute = AdminAdminCatRequestsRouteImport.update({
  id: '/admin/cat-requests',
  path: '/admin/cat-requests',
  getParentRoute: () => AdminRoute,
} as any)
const LangLandingPrivacyPolicyRoute =
  LangLandingPrivacyPolicyRouteImport.update({
    id: '/privacy-policy',
    path: '/privacy-policy',
    getParentRoute: () => LangLandingRoute,
  } as any)
const LangLandingFaqRoute = LangLandingFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LangLandingRoute,
} as any)
const LangLandingContactUsRoute = LangLandingContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => LangLandingRoute,
} as any)
const LangAuthResetPasswordRoute = LangAuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => LangAuthRoute,
} as any)
const LangAuthRegisterRoute = LangAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LangAuthRoute,
} as any)
const LangAuthLoginRoute = LangAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LangAuthRoute,
} as any)
const LangAuthForgotPasswordRoute = LangAuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => LangAuthRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$lang': typeof LangLandingRouteWithChildren
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/$lang/forgot-password': typeof LangAuthForgotPasswordRoute
  '/$lang/login': typeof LangAuthLoginRoute
  '/$lang/register': typeof LangAuthRegisterRoute
  '/$lang/reset-password': typeof LangAuthResetPasswordRoute
  '/$lang/contact-us': typeof LangLandingContactUsRoute
  '/$lang/faq': typeof LangLandingFaqRoute
  '/$lang/privacy-policy': typeof LangLandingPrivacyPolicyRoute
  '/admin/cat-requests': typeof AdminAdminCatRequestsRoute
  '/admin/contact-us': typeof AdminAdminContactUsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/$lang/': typeof LangLandingIndexRoute
  '/$lang/map': typeof LangMapIndexRoute
  '/$lang/report-found-cat': typeof LangReportFoundCatIndexRoute
  '/$lang/report-lost-cat': typeof LangReportLostCatIndexRoute
  '/admin': typeof AdminAdminIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/$lang': typeof LangLandingIndexRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/$lang/forgot-password': typeof LangAuthForgotPasswordRoute
  '/$lang/login': typeof LangAuthLoginRoute
  '/$lang/register': typeof LangAuthRegisterRoute
  '/$lang/reset-password': typeof LangAuthResetPasswordRoute
  '/$lang/contact-us': typeof LangLandingContactUsRoute
  '/$lang/faq': typeof LangLandingFaqRoute
  '/$lang/privacy-policy': typeof LangLandingPrivacyPolicyRoute
  '/admin/cat-requests': typeof AdminAdminCatRequestsRoute
  '/admin/contact-us': typeof AdminAdminContactUsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/$lang/map': typeof LangMapIndexRoute
  '/$lang/report-found-cat': typeof LangReportFoundCatIndexRoute
  '/$lang/report-lost-cat': typeof LangReportLostCatIndexRoute
  '/admin': typeof AdminAdminIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$lang': typeof LangRouteWithChildren
  '/_admin': typeof AdminRouteWithChildren
  '/$lang/_auth': typeof LangAuthRouteWithChildren
  '/$lang/_landing': typeof LangLandingRouteWithChildren
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/$lang/_auth/forgot-password': typeof LangAuthForgotPasswordRoute
  '/$lang/_auth/login': typeof LangAuthLoginRoute
  '/$lang/_auth/register': typeof LangAuthRegisterRoute
  '/$lang/_auth/reset-password': typeof LangAuthResetPasswordRoute
  '/$lang/_landing/contact-us': typeof LangLandingContactUsRoute
  '/$lang/_landing/faq': typeof LangLandingFaqRoute
  '/$lang/_landing/privacy-policy': typeof LangLandingPrivacyPolicyRoute
  '/_admin/admin/cat-requests': typeof AdminAdminCatRequestsRoute
  '/_admin/admin/contact-us': typeof AdminAdminContactUsRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/$lang/_landing/': typeof LangLandingIndexRoute
  '/$lang/map/': typeof LangMapIndexRoute
  '/$lang/report-found-cat/': typeof LangReportFoundCatIndexRoute
  '/$lang/report-lost-cat/': typeof LangReportLostCatIndexRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$lang'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/$lang/forgot-password'
    | '/$lang/login'
    | '/$lang/register'
    | '/$lang/reset-password'
    | '/$lang/contact-us'
    | '/$lang/faq'
    | '/$lang/privacy-policy'
    | '/admin/cat-requests'
    | '/admin/contact-us'
    | '/admin/users'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/$lang/'
    | '/$lang/map'
    | '/$lang/report-found-cat'
    | '/$lang/report-lost-cat'
    | '/admin'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$lang'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/$lang/forgot-password'
    | '/$lang/login'
    | '/$lang/register'
    | '/$lang/reset-password'
    | '/$lang/contact-us'
    | '/$lang/faq'
    | '/$lang/privacy-policy'
    | '/admin/cat-requests'
    | '/admin/contact-us'
    | '/admin/users'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/$lang/map'
    | '/$lang/report-found-cat'
    | '/$lang/report-lost-cat'
    | '/admin'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/$lang'
    | '/_admin'
    | '/$lang/_auth'
    | '/$lang/_landing'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/$lang/_auth/forgot-password'
    | '/$lang/_auth/login'
    | '/$lang/_auth/register'
    | '/$lang/_auth/reset-password'
    | '/$lang/_landing/contact-us'
    | '/$lang/_landing/faq'
    | '/$lang/_landing/privacy-policy'
    | '/_admin/admin/cat-requests'
    | '/_admin/admin/contact-us'
    | '/_admin/admin/users'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/$lang/_landing/'
    | '/$lang/map/'
    | '/$lang/report-found-cat/'
    | '/$lang/report-lost-cat/'
    | '/_admin/admin/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LangRoute: typeof LangRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/_landing': {
      id: '/$lang/_landing'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangLandingRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_auth': {
      id: '/$lang/_auth'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangAuthRouteImport
      parentRoute: typeof LangRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$lang/report-lost-cat/': {
      id: '/$lang/report-lost-cat/'
      path: '/report-lost-cat'
      fullPath: '/$lang/report-lost-cat'
      preLoaderRoute: typeof LangReportLostCatIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/report-found-cat/': {
      id: '/$lang/report-found-cat/'
      path: '/report-found-cat'
      fullPath: '/$lang/report-found-cat'
      preLoaderRoute: typeof LangReportFoundCatIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/map/': {
      id: '/$lang/map/'
      path: '/map'
      fullPath: '/$lang/map'
      preLoaderRoute: typeof LangMapIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_landing/': {
      id: '/$lang/_landing/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangLandingIndexRouteImport
      parentRoute: typeof LangLandingRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/contact-us': {
      id: '/_admin/admin/contact-us'
      path: '/admin/contact-us'
      fullPath: '/admin/contact-us'
      preLoaderRoute: typeof AdminAdminContactUsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/cat-requests': {
      id: '/_admin/admin/cat-requests'
      path: '/admin/cat-requests'
      fullPath: '/admin/cat-requests'
      preLoaderRoute: typeof AdminAdminCatRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$lang/_landing/privacy-policy': {
      id: '/$lang/_landing/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/$lang/privacy-policy'
      preLoaderRoute: typeof LangLandingPrivacyPolicyRouteImport
      parentRoute: typeof LangLandingRoute
    }
    '/$lang/_landing/faq': {
      id: '/$lang/_landing/faq'
      path: '/faq'
      fullPath: '/$lang/faq'
      preLoaderRoute: typeof LangLandingFaqRouteImport
      parentRoute: typeof LangLandingRoute
    }
    '/$lang/_landing/contact-us': {
      id: '/$lang/_landing/contact-us'
      path: '/contact-us'
      fullPath: '/$lang/contact-us'
      preLoaderRoute: typeof LangLandingContactUsRouteImport
      parentRoute: typeof LangLandingRoute
    }
    '/$lang/_auth/reset-password': {
      id: '/$lang/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/$lang/reset-password'
      preLoaderRoute: typeof LangAuthResetPasswordRouteImport
      parentRoute: typeof LangAuthRoute
    }
    '/$lang/_auth/register': {
      id: '/$lang/_auth/register'
      path: '/register'
      fullPath: '/$lang/register'
      preLoaderRoute: typeof LangAuthRegisterRouteImport
      parentRoute: typeof LangAuthRoute
    }
    '/$lang/_auth/login': {
      id: '/$lang/_auth/login'
      path: '/login'
      fullPath: '/$lang/login'
      preLoaderRoute: typeof LangAuthLoginRouteImport
      parentRoute: typeof LangAuthRoute
    }
    '/$lang/_auth/forgot-password': {
      id: '/$lang/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/$lang/forgot-password'
      preLoaderRoute: typeof LangAuthForgotPasswordRouteImport
      parentRoute: typeof LangAuthRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LangAuthRouteChildren {
  LangAuthForgotPasswordRoute: typeof LangAuthForgotPasswordRoute
  LangAuthLoginRoute: typeof LangAuthLoginRoute
  LangAuthRegisterRoute: typeof LangAuthRegisterRoute
  LangAuthResetPasswordRoute: typeof LangAuthResetPasswordRoute
}

const LangAuthRouteChildren: LangAuthRouteChildren = {
  LangAuthForgotPasswordRoute: LangAuthForgotPasswordRoute,
  LangAuthLoginRoute: LangAuthLoginRoute,
  LangAuthRegisterRoute: LangAuthRegisterRoute,
  LangAuthResetPasswordRoute: LangAuthResetPasswordRoute,
}

const LangAuthRouteWithChildren = LangAuthRoute._addFileChildren(
  LangAuthRouteChildren,
)

interface LangLandingRouteChildren {
  LangLandingContactUsRoute: typeof LangLandingContactUsRoute
  LangLandingFaqRoute: typeof LangLandingFaqRoute
  LangLandingPrivacyPolicyRoute: typeof LangLandingPrivacyPolicyRoute
  LangLandingIndexRoute: typeof LangLandingIndexRoute
}

const LangLandingRouteChildren: LangLandingRouteChildren = {
  LangLandingContactUsRoute: LangLandingContactUsRoute,
  LangLandingFaqRoute: LangLandingFaqRoute,
  LangLandingPrivacyPolicyRoute: LangLandingPrivacyPolicyRoute,
  LangLandingIndexRoute: LangLandingIndexRoute,
}

const LangLandingRouteWithChildren = LangLandingRoute._addFileChildren(
  LangLandingRouteChildren,
)

interface LangRouteChildren {
  LangAuthRoute: typeof LangAuthRouteWithChildren
  LangLandingRoute: typeof LangLandingRouteWithChildren
  LangMapIndexRoute: typeof LangMapIndexRoute
  LangReportFoundCatIndexRoute: typeof LangReportFoundCatIndexRoute
  LangReportLostCatIndexRoute: typeof LangReportLostCatIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAuthRoute: LangAuthRouteWithChildren,
  LangLandingRoute: LangLandingRouteWithChildren,
  LangMapIndexRoute: LangMapIndexRoute,
  LangReportFoundCatIndexRoute: LangReportFoundCatIndexRoute,
  LangReportLostCatIndexRoute: LangReportLostCatIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

interface AdminRouteChildren {
  AdminAdminCatRequestsRoute: typeof AdminAdminCatRequestsRoute
  AdminAdminContactUsRoute: typeof AdminAdminContactUsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminCatRequestsRoute: AdminAdminCatRequestsRoute,
  AdminAdminContactUsRoute: AdminAdminContactUsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LangRoute: LangRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
